---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: chaostoolkit
  name: chaostoolkit-results
spec:
  capacity:
    storage: 250Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/log/chaostoolkit